# Define a dictionary to map role names to emojis
role_emoji_map = {
    "Vivid": "✅",
    "Chalkboard": "💬",
    "Underdog": "📱",
    "Betr": "🎮",
    "Dabble": "🏆",
    "WannaParlay": "🏀",
    "FanDuel": "⚽",
    "DraftKings": "👑",
    "Bet365": "💸",
    "Sleeper": "💥",
    "Caesars": "👑",
    "Bet99": "🎯",
    "Stake": "🔥",
    "WynnBet": "🍀",
    "Pinnacle": "⭐",
    "ESPN": "🏀",
    "UBet": "🎯",
    "TheScore": "📊",
    "TonyBet": "💰",
    "Prize Picks": "🎮",
}
