# fly.toml app configuration file generated for ai-picks on 2025-04-01T00:13:39-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-picks'
primary_region = 'yul'

[experimental]
  auto_rollback = true

[build]
  dockerfile = 'Dockerfile'

[processes]
  app = 'python DiscordBot/bot.py'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
