bad_words = [
    "nigger",
    "jew",
    "faggot",
    "DM",
    "dm me",
    "dm",
    "D.M.",
    "dM",
    "d.m.",
    "D.M",
    "Direct Message",
    "Direct Msg",
    "P.M.",
    "P.M",
    "Pm",
    "Private Message",
    "Priv M",
    "Pr1v@te M",
    "Slide into DMs",
    "Slide into my D.M.s",
    "Slide in DMs",
    "Ping me",
    "Ping me in DM",
    "Send me a DM",
    "Send me a D.M.",
    "S3nd me a DM",
    "Send me a p.m.",
    "Send me a private",
    "D.m me",
    "D.M. me",
    "Dm me",
    "DM me",
    "Message me",
    "M€ss@g€ me",
    "M€ss@g€",
    "M.E.S.S.A.G.E me",
    "Sh00t me a DM",
    "Sh00t me a p.m.",
    "Message me privately",
    "Contact me directly",
    "Private msg me",
    "PM me",
    "Pm me",
    "P.M me",
    "Private message me",
    "Send me a private",
    "Hit me up in DM",
    "Drop me a DM",
    "Send a private",
    "Contact me in DM",
    "Reach out via DM",
    "Message me directly",
    "Text me privately",
    "Contact me via DM",
    "Send me a message",
    "Shoot me a message",
    "Ping me",
    "Send me a text",
    "Text me",
    "Message me",
    "P.M. me",
    "DM me",
    "Slide me a message",
    "Direct me a message",
    "Send me a DM",
    "Send me a P.M.",
    "Reach me via message",
    "Message me privately",
    "Direct message me",
    "Send me a text",
    "Slide into my messages",
    "Drop me a message",
    "Ping me privately",
    "Contact me",
    "Drop me a text",
    "Send me a quick message",
    "Send a private message",
    "Send me a quick DM",
    "Sh00t me a message",
    "Contact me via text",
    "Text me privately",
    "Send me an IM",
    "P.M me a message",
    "PM me for more info",
    "Send me a direct message",
    "D.M me",
    "Send me a private DM",
    "P.M me now"
]